server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/shipping-service
      auto-index-creation: true

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.pycogroup.training: DEBUG

rest:
  clients:
    order: localhost:8086/orders
    customer: localhost:8089/customers
