server:
  port: 8089

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-service
      auto-index-creation: true
  cloud:
    stream:
      kafka: # kafka message broker
        binder:
          brokers: localhost:9092
          replicationFactor: 1

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.pycogroup.training: DEBUG