server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service
  cloud:
    stream:
      kafka: # kafka message broker
        binder:
          brokers: localhost:9092
          replicationFactor: 1
      bindings:
        input: # channel:in => consumer
          destination: orders_verifed_possibility # topic
          consumer:
            resetOffsets: true
            startOffset: latest
        output: # channel:out => producer
          destination: orders_created # topic
          producer:
            partitionKeyExpression: payload.customerId
            partitionCount: 2 # the number of groups (orders_account & orders_product)

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.pycogroup.training: DEBUG