server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service
      auto-index-creation: true
  cloud:
    stream:
      kafka: # kafka message broker
        binder:
          brokers: localhost:9092
          replicationFactor: 1
      bindings:
        input: # channel:in => consumer
          destination: top-orders-verified # topic
          group: grp-orders-verified
          consumer:
            resetOffsets: true
            startOffset: latest
        output: # channel:out => producer
          destination: top-orders-created # topic
          producer:
            partitionKeyExpression: payload.customerId

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.pycogroup.training: DEBUG