server:
  port: 8086
  servlet:
    context-path: /order

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.pycogroup.training: DEBUG